test:
  docker:
    - image: circleci/python:3.8.4
  steps:
    - checkout
    - restore_cache:
      key: deps-{{ checksum "requirements.lock" }}
    - run:
        command: |
          python3 -m unittest -v
workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
          requires:
            - setup_dependencies
